# Generated by Django 4.1.7 on 2023-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('holder', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=20)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
