# Generated by Django 4.1.7 on 2023-03-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creditcardapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_date', models.DateField()),
                ('holder', models.CharField(max_length=128)),
                ('number', models.CharField(max_length=20)),
                ('cvv', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creditcardapi.creditcardbrand')),
            ],
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
