# Generated by Django 4.1.7 on 2023-03-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcardapi', '0002_creditcardbrand_creditcardmodel_delete_creditcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcardmodel',
            name='sal',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='cvv',
            field=models.IntegerField(blank=True),
        ),
    ]
