# Generated by Django 4.1.7 on 2023-03-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcardapi', '0003_creditcardmodel_sal_alter_creditcardmodel_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardmodel',
            name='number',
            field=models.CharField(max_length=1024),
        ),
    ]
