# Generated by Django 4.1.7 on 2023-03-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditcardapi', '0004_alter_creditcardmodel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardmodel',
            name='sal',
        ),
        migrations.AlterField(
            model_name='creditcardmodel',
            name='number',
            field=models.TextField(),
        ),
    ]
